create table associado (
    id int not null primary key auto_increment,
    nome varchar(255) not null,
    sexo varchar(255) not null,
    cpf varchar(255) not null unique,
    contato varchar(255) not null,
    email varchar(255) not null unique,
    rg varchar(15) not null unique,
    dtn date not null,
    matricula varchar(255) not null unique,
    datadeFiliacao date,
    regimedetrabalho varchar(150) not null,
    enderecoSegurado varchar(150) not null,
    numero varchar(150) not null,
    bairro varchar(150) not null,
    cep varchar(150) not null,
    cidade varchar(150) not null,
    uf varchar(150) not null,
    pontoreferencia varchar(150) not null,
    confrontantesviz varchar(150) not null,
    idcategoria int not null,
    idpropriedaderural int not null,
    idprofissao int not null,	
    idassociacao int not null,
    estadocivil varchar(100) not null,
    ctps_ct varchar(50) not null,
    apelido varchar(100),
    foreign key (idcategoria) references categoria(idcategoria),
    foreign key (idprofissao) references profissao(idprofissao),
    foreign key (idpropriedaderural) references propriedaderural(id),
    foreign key (idassociacao) references associacao(id)
);